# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,1

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
exec-once = /home/dilip/.config/hypr/autostart &

# Source a file (multi-file configs)
source=~/.config/hypr/themes/popos/mocha.conf

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 8
    gaps_out = 15
    border_size = 3
    col.active_border = $accent
    # col.active_border = $mauve $teal 45deg
    col.inactive_border = $surface0

    layout = master

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    rounding = 10

    blur {
        enabled = true
        size = 8
        passes = 1
    }

    active_opacity = 0.9
    inactive_opacity = 0.9
    fullscreen_opacity = 0.9
    drop_shadow = no
    shadow_range = 5
    shadow_render_power = 10
    col.shadow = $base
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

