gui:
  border: rounded
  showIcons: false
  theme:
    activeBorderColor:
      - '#ea6962'
      - bold
    inactiveBorderColor:
      - '#89b482'
    optionsTextColor:
      - '#7daea3'
    selectedLineBgColor:
      - '#45403d'
    selectedLineFgColor:
      - '#d4be98'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#c6a0f6'
    unstagedChangesColor:
      - '#d4be98'
    defaultFgColor:
      - '#d4be98'
    searchingActiveBorderColor:
      - '#d8a657'

  authorColors:
    '*': '#d3869b'

  spinner:
    frames:
     - '⠋'
     - '⠙'
     - '⠹'
     - '⠸'
     - '⠼'
     - '⠴'
     - '⠦'
     - '⠧'
     - '⠇'
     - '⠏'
git:
  parseEmoji: true
