gui:
  border: rounded
  showIcons: false
  theme:
    activeBorderColor:
      - '#ef596f'
      - bold
    inactiveBorderColor:
      - '#2bbac5'
    optionsTextColor:
      - '#61afef'
    selectedLineBgColor:
      - '#2bbac5'
    selectedLineFgColor:
      - '#2bbac5'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#c6a0f6'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#abb2bf'
    searchingActiveBorderColor:
      - '#e5c07b'

  authorColors:
    '*': '#b7bdf8'

  spinner:
    frames:
     - '⠋'
     - '⠙'
     - '⠹'
     - '⠸'
     - '⠼'
     - '⠴'
     - '⠦'
     - '⠧'
     - '⠇'
     - '⠏'
git:
  parseEmoji: true
