name = "screenshots"
name_pretty = "Screenshots"
# icon = "camera-photo"
global_search = true

[[entries]]
text = "View"
icon = "viewimage"
actions = { "view" = "vimiv $HOME/Pictures/" }

[[entries]]
text = "Screenshot screen"
icon = "window_fullscreen"
actions = { "screen" = "grim $DIR$NAME && notify-send 'Grim' 'Screenshot saved.' -i $DIR$NAME -t 2000" }

[[entries]]
text = "Screenshot Region"
icon = "select-rectangular"
actions = { "region" = "grim -g '$(slurp)' $DIR$NAME && notify-send 'Grim' 'Screenshot saved.' -i 'dialog-information' -t 2000" }
