#!/usr/bin/bash

# swww-daemon &
hyprpaper &
waybar --config ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css &
wally -r &
mpd &
nm-applet &
# swaync --config ~/.config/swaync/themes/minimal/config.json --style ~/.config/swaync/themes/minimal/style.css &
kdeconnect-indicator &
