#!/usr/bin/bash

swww-daemon &
# hyprpaper &
waybar --config ~/.config/waybar/confs/float-panel/config-vert.jsonc -s ~/.config/waybar/confs/float-panel/style-vert.css &
wally -r &
mpd &
nm-applet &
swaync --config ~/.config/swaync/config.json --style ~/.config/swaync/style.css &
elephant &
walker --gapplication-service &
