command_timeout = 1000
# format = """
# $hostname\
# $shell\
# ${custom.yazi}\
# $username\
# $sudo\
# $character\
# """
format = '$all'
# move the rest of the prompt to the right
# right_format = """${custom.yazi}"""

# Sets the palette to "one_dark".
palette = 'one_dark'

[character]
# Note the use of Catppuccin color 'maroon'

success_symbol = "[[](color_green) ❯](color_red0)"
error_symbol = "[[](color_red0) ❯](color_red0)"
vimcmd_symbol = "[[](color_green) ❮](color_green)"

# Sets the colors of the "one_dark" palette.
[palettes.one_dark]
mono0 = '#d7dae0' # terminal white, from the One Dark Pro VSCode theme.
mono1 = '#abb2bf' # syntax_fg.
mono2 = '#828997'
mono3 = '#5c6370'
mono4 = '#3f4451' # terminal black, from the One Dark Pro VSCode theme.
color_red0 = '#e06c75'
color_red1 = '#be5046'
color_green = '#98c379'
color_yellow = '#e5c07b'
color_blue = '#61afef'
color_purple = '#c678dd'
color_cyan = '#56b6c2'
color_orange = '#d19a66'
syntax_fg = '#abb2bf'
syntax_bg = '#282c34'
color_bg2 = '#665c54'
syntax_gutter = '#647382'
syntax_accent = '#528cff'

[custom.yazi]
description = "Indicate the shell was launched by `yazi`"
symbol = "  Yazi Terminal "
when = """ test -n "$YAZI_LEVEL" """

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
home_symbol = " "
read_only_style = 'red'
read_only = "  "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "
